### ISSUE TITLE
Initial seed

### ISSUE THREAD

**Issue by StepanSushko** [I3ck/cppOpt#1]
Hey,
is there way to define initial seed in order to have reproducibility of results?

Thx in advance

**Comment by I3ck** [comment]
Should be quite easy to implement.
Do you actually need this functionality or just wondering?
And do you want reproduceable-randomness, or to be able to directly define "the first calculation" ?

**Comment by StepanSushko** [comment]
I'd like to have reproducible randomness for my PhD project. I use Simulated Annealing btw.

**Comment by I3ck** [comment]
Added with https://github.com/I3ck/cppOpt/commit/5ef98fc07fc212033d04a14539f59b9ebdf83456 
Make sure to only run on one thread to have more reproduceable results.
Feel free opening new issues / telling me what you're working on, since I'm interested in all use cases :)
Have a nice day
