### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by StepanSushko** [I3ck/cppOpt#2]
I have to optimize (calibrate) function with 3 parameters of different scale. One parameter is in the range (1, 2), another two are around (0.01). It looks like the algorithm (SA) checks only relatively large values (for example 0.4, 0.85, 0.1) and run over the others (smaller ones). In other words it doesn't check values which are cloth to real ones (0.005, 0.007, 0.012).

p.s. thx for reproducible randomness

**Comment by I3ck** [comment]
could you copy&paste your setup? Definition of boundaries etc. similar as in the examples

**Comment by StepanSushko** [comment]
> using namespace cppOpt;
> 
> template <typename T>
> class MySolver : public OptSolverBase<T>
> {
> public:
>   void calculate(OptCalculation<T> &optCalculation) const
>   {
>       //defined x^2 as function to be optimised
>       cout        << optCalculation.get_parameter("m0")
>            << "," << optCalculation.get_parameter("sigma")
>            << "," << optCalculation.get_parameter("rho")
>            << endl;
>       optCalculation.result = pow(optCalculation.get_parameter("m0") - 1.4f, 2) + >pow(optCalculation.get_parameter("sigma") - 0.02f, 2) + pow(optCalculation.get_parameter("rho") - 0.01f, 2);
>   }
> };

I've made a wrapper:

> void optSA(float\* optimum, unsigned int maxCalculations, int seed)
> {
>   OptBoundaries<float> optBoundaries;
>   optBoundaries.add_boundary(1.0f, 2.0f, "m0");
>   optBoundaries.add_boundary(0.000001f, 0.1f, "sigma");
>   optBoundaries.add_boundary(0.0f, 0.1f, "rho");
> 
> ```
>   //instansiate your calculator
> ```
> 
>   MySolver<float> mySolver;
> 
> ```
>   //we want to find the minimum
> ```
> 
>   OptTarget optTarget = MINIMIZE;
> 
> ```
>   //how fast the simulated annealing algorithm slows down
>   //http://en.wikipedia.org/wiki/Simulated_annealing
> ```
> 
>   float coolingFactor = 0.95f;//0.95f;
> 
> ```
>                           //the chance in the beginning to follow bad solutions
> ```
> 
>   float startChance = 0.5f; // 0.25f;
> 
> ```
>                         //create your optimiser
>                         //using simulated annealing
> ```
> 
>   OptSimulatedAnnealing<float> optSA(optBoundaries,
>       maxCalculations,
>       &mySolver,
>       optTarget,
>       0.0, //only required if approaching / diverging
>       coolingFactor,
>       startChance);
> 
> ```
>   //enable logging
>   //boundaries object required to know the parameters names for the header
>   //OptBase<float>::enable_logging("example_simulated_annealing_x_square.log", optBoundaries);
> 
>   //let's go
> ```
> 
>   OptBase<float>::run_optimisations(1, seed);
> 
> ```
>   //print result
> ```
> 
>   OptCalculation<float> best = optSA.get_best_calculation();
>   optimum[0] = (float)(best.get_parameter("m0"));
>   optimum[1] = (float)(best.get_parameter("sigma"));
>   optimum[2] = (float)(best.get_parameter("rho"));
> }

Seed is `4294967291`, `maxCalculations = 300`, real minimum is `(1.4, 0.02, 0.01)`. In these settings SA converges to 

> m0 =1.40036,
> sigma = 0.0438227,
> rho = 0.0170878

If `seed = 2912441431`

> 1.40012,0.0368495,0.0463739

As you see, it converges much better in case of `m0` variable.

**Comment by I3ck** [comment]
I think this happens since m0 plays the highest role in the overall result.
Can you try assigning small ranges / values to all 3 of them and check again?
I think this is no bug, but just how the optimization behaves

**Comment by StepanSushko** [comment]
It's not a bug. I can make ranges very small, but in this case they would be artificially small. I use the range which is teoretically reasonable, I cannot do it smaller. Some algorithms (for example Landenberg-Marquart algorithm) have possibility to scale variables. So, I wonder it is possible to do for SA somehow.

**Comment by I3ck** [comment]
have you tried

``` cpp
std::cout << setprecision(10);
```

?

**Comment by I3ck** [comment]
Feel free to re-open this or another issue if this didn't help
