### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by StepanSushko** [I3ck/cppOpt#3]
In `OptBase.h`, I get warning `Warning  C4244   '=': conversion from 'double' to 'float', possible loss of data' which leads to error in 'T calculate_random_change(const OptBoundary<T> &boundary, T temperature) const` in the case when I use `float` type. 

I fixed by myself as

> maxChange = (T)0.5 \* (T)boundary.range() \* (T)temperature;

**Comment by I3ck** [comment]
Can you test it with https://github.com/I3ck/cppOpt/commit/0ed54ebc4f558ca94129d772961757d657965805 
and tell me whether it worked / close this issue?
Thanks

**Comment by StepanSushko** [comment]
Yes, it's fine now. Thx.
