### ISSUE TITLE
Memory leak in OptBase

### ISSUE THREAD

**Issue by arunkandanchatha** [I3ck/cppOpt#4]
I am writing code where I call the optimisation routine thousands of times. It appears that results are all stored in OptBase::finishedCalculations, which is static, and therefore never freed. As a result, memory usage explodes.

Clearing the vector after every call to OptBase::run_optimisations() fixes the issue for me (though may not be in the spirit of what you've written).

**Comment by I3ck** [comment]
I planned on adding a resetStaticState method.  
My use case was basically only running it once after setup.

**Comment by I3ck** [comment]
Should now be possible to reset via https://github.com/I3ck/cppOpt/commit/1cd7e391746d5b7f00b3b390c78ea8f22123e536 .  
Can you try it, and comment / close afterwards?  
Also I'd love to hear what you use it for, if that's ok

**Comment by I3ck** [comment]
I'll close it, feel free to re-open if there's still an issue
