### ISSUE TITLE
Visual Studio 2017 RC compilation error

### ISSUE THREAD

**Issue by StepanSushko** [I3ck/cppOpt#5]
Hey, there is an issue with VS2017RC: "there was an unhandled exception at 0x7456A832 of Microsoft C ++:. Std :: system_error at memory 0x08D5EB58."

It happens on line 153 of the file OptBase.h 
        
`threads.emplace_back(  std::thread( std::bind(&OptBase::threaded_work) )  );`

I hope it is easy to fix. Thanks in advance!

**Comment by I3ck** [comment]
Does that happen with the examples or your own code? I have no access to VS, so I can't debug it :/

**Comment by StepanSushko** [comment]
It happens with my code, which is worked fine with the previous version of VS and is copy/paste of the examples. It compiles fine in Debug mode, but while I start a debugging procedure I got the error above.

**Comment by I3ck** [comment]
Could you post the call stack?

**Comment by StepanSushko** [comment]
I've created an empty project, copypasted everything from *example_simulated_annealing_x_square.cpp* to the mainfile.cpp. It compiles, but again it gets stucked  on debuging step (line 46 of OptSimulatedAnnealing.h)

>       super(optBoundaries, maxCalculations, pCalculator, optTarget, targetValue),

*xthread* (line 85)

> inline int _Mtx_unlockX(_Mtx_t _Mtx)
	{	// throw exception on failure
	return (_Check_C_return(_Mtx_unlock(_Mtx)));
	}

Call stack:

> 	Ucrtbased.dll! 100096b1 () No Information
 [The following frames may be wrong and (or) missing, symbols are loaded for ucrtbased.dll]
 [External Code]
 ConsoleApplication1.exe! Std :: _ Mtx_unlockX (_Mtx_internal_imp_t * _Mtx) Line 85 C ++
 ConsoleApplication1.exe! Std :: _ Mutex_base :: unlock () Line 53 C ++
 ConsoleApplication1.exe! Std :: lock_guard <std :: mutex> :: ~ lock_guard <std :: mutex> () Line 229 C ++
 ConsoleApplication1.exe! CppOpt :: OptBase <double> :: OptBase <double> (const cppOpt :: OptBoundaries <double> & optBoundaries, unsigned int maxCalculations, cppOpt :: OptSolverBase <double> * pCalculator, cppOpt :: OptTarget optTarget, double targetValue) Line 121 C ++
 ConsoleApplication1.exe! CppOpt :: OptSimulatedAnnealing <double> :: OptSimulatedAnnealing <double> (const cppOpt :: OptBoundaries <double> & optBoundaries, unsigned int maxCalculations, cppOpt :: OptSolverBase <double> * pCalculator, cppOpt :: OptTarget optTarget, double targetValue, double coolingFactor, double startChance) Line 50 C ++
 ConsoleApplication1.exe! Main () Line 65 C ++
 [External Code]

**Comment by I3ck** [comment]
Can you reproduce the issue with other versions of VS?

**Comment by StepanSushko** [comment]
I'm not able to insall the previous version of VS, but the code worked with it, I didn't changed it.

**Comment by StepanSushko** [comment]
Hey, I tried to create empty project with copy/paste of examples. This error still persists...

p.s. I use VS2017 Community

**Comment by I3ck** [comment]
I'll have a windows machine rather soonish. I can try to reproduce and fix it then.

**Comment by I3ck** [comment]
I finally managed to get a windows machine with VS17. https://github.com/I3ck/cppOpt/commit/beb77859eb11cf8df4107e58e703f9b9203ff6a2 should resolve your issue

**Comment by StepanSushko** [comment]
Hey, thank you!

I tried it to compile. VS throws an warning in OptBase.h at line the 134

> warning C4244: '=' : conversion from 'time_t' to 'unsigned int', possible loss of data

I changed it to 
`        run_optimisations(maxThreads, (unsigned int)time(NULL));`

Also, there is some mess with user defined seed intialization, I need more tests. I'll write about it with more details latter on.

**Comment by I3ck** [comment]
Alright. Thanks for your patience and good luck. Just open another issue if the seed initalization is bugged

**Comment by StepanSushko** [comment]
Hey,
I have weird situation. When I create empty project and paste the example there It compiles and works fine, but If paste the same example in my project it throws an error in the same place of `optBase.h` as before, but in `xthread` it stops on the line 36
`inline int _Check_C_return(int _Res)
	{	// throw exception on failure
	if (_Res != _Thrd_success)
		_Throw_C_error(_Res);
	return (_Res);
	}`
